### ISSUE TITLE
branch ambiguously defined for ImageUpdateAutomation as well as for git repo

### ISSUE THREAD

**Issue by davidkarlsen** [fluxcd/image-automation-controller#113]
https://toolkit.fluxcd.io/guides/image-update/:
ImageUpdateAutomation takes a branch parameter, but so does the git-repo it refers, this seems ambiguous to me, you want to refer the git repo it was defined in, and that's already defined in the GitRepository - hence it should be sufficient with the gitRepositoryRef.

spec:
  checkout:
    branch: main <-- 
    gitRepositoryRef:
      name: flux-system <-- this repo already has a branch defined

Maybe a bit related to https://github.com/fluxcd/image-automation-controller/issues/85

**Comment by squaremo** [comment]
Also pertinent: the discussion in https://github.com/fluxcd/flux2/discussions/665

**Comment by pjbgf** [comment]
@davidkarlsen thank you for reporting this. This has been fixed in version [v0.9.0](https://github.com/fluxcd/image-automation-controller/blob/main/CHANGELOG.md#090) with the introduction of API version `v1alpha2`.

The [change](https://github.com/fluxcd/image-automation-controller/commit/ebb2d6abea9a6eccfdde1d263adbb74b57fac43f) allows for `ImageUpdateAutomation` to optionally set checkout references in the same way as in the `GitRepository` objects and when not set it defaults to the value set in the `GitRepository` references to by the `sourceRef` field.

For more information, including the migration path, please check the [documentation](https://fluxcd.io/docs/components/image/imageupdateautomations/).

I will be closing this issue now, but feel free add a comment here in case you want this reopened.
