### ISSUE TITLE
Add [info] message to log output showing reconcile attempt

### ISSUE THREAD

**Issue by cdavisafc** [fluxcd/image-automation-controller#181]
Currently the controller does not show any message when a reconciliation attempt is made but there is no action. This made me wonder if the reconciliation loop was somehow broken. It would be helpful to have a message on each attempt (such as done by the image reflector controller).

**Comment by squaremo** [comment]
There are many more reconciliations than there are actions taken, so there's no useful signal in logging when a reconciliation is run and has no effect. Or to put it another way: you may as well assume reconciliation is running constantly, and it's only when it does something that matters (or another way: it's level triggered).

I think what you wanted is to see is that when you had taken a specific action (like creating or updating an image automation), it had noticed the change but not had an effect on the git repo. A better place to look is the automation object status, which will tell you when it ran last, what happened, and what was the last commit it made. E.g.,

```
kubectl describe imageupdateautomation
# ... the metadata and spec ...
Status:
  Conditions:
    Last Transition Time:    2021-06-09T14:26:37Z
    Message:                 no updates made; last commit b6e4878 at 2021-06-09T16:04:09+01:00
    Reason:                  ReconciliationSucceeded
    Status:                  True
    Type:                    Ready
  Last Automation Run Time:  2021-06-09T16:40:32Z
  Last Push Commit:          b6e487814b4fcd01cd3aca7731d59720fe1aebae
  Last Push Time:            2021-06-09T15:04:09Z
  Observed Generation:       1
Events:
  Type    Reason  Age                     From                         Message
  ----    ------  ----                    ----                         -------
  Normal  info    4m18s (x116 over 114m)  image-automation-controller  no updates made
```

Hence or otherwise, there is debug-level logging output every time through the reconciliation loop, which might help troubleshoot why something _didn't_ happen -- i.e., for debugging.

**Comment by kingdonb** [comment]
So I think we're saying this could be a "debug" message, rather than "info"

Sounds like a good first issue

**Comment by squaremo** [comment]
> So I think we're saying this could be a "debug" message, rather than "info"

I said that there is already debug-level output, and that reporting (only) that the reconciliation loop ran is not helpful. I'm going to close this, to take it off the radar.
