### ISSUE TITLE
executing kustomize build | kubectl apply -f- led to ImagePullBackOff

### ISSUE THREAD

**Issue by fbrv** [fluxcd/image-automation-controller#51]
Hi,
Following the suggestion on slack I took a look to this repository to experiment a bit with the image-automation-controller and, maybe in the future, contribute to this really interesting project.  
Once I've cloned the repository I navigated to /config/default folder and I launched the following command:
```
kustomize build | kubectl apply -f-
```
Checking the status of the image-automation-controller I saw that is in status ImagePullBackOff.  
Looking for the events, I go these ones:
```
  Normal   Pulled     80s                kubelet            Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0" already present on machine
  Normal   Created    80s                kubelet            Created container kube-rbac-proxy
  Normal   Started    80s                kubelet            Started container kube-rbac-proxy
  Normal   Pulling    40s (x3 over 80s)  kubelet            Pulling image "fluxcd/image-automation-controller"
  Warning  Failed     39s (x3 over 79s)  kubelet            Failed to pull image "fluxcd/image-automation-controller": rpc error: code = Unknown desc = Error response from daemon: manifest for fluxcd/image-automation-controller:latest not found: manifest unknown: manifest unknown
  Warning  Failed     39s (x3 over 79s)  kubelet            Error: ErrImagePull
  Normal   BackOff    6s (x5 over 78s)   kubelet            Back-off pulling image "fluxcd/image-automation-controller"
  Warning  Failed     6s (x5 over 78s)   kubelet            Error: ImagePullBackOff
```
After a quick search inside the fluxcd repository I saw that no container is tagged as latest and this is causing the error, the only tag present is: v0.0.1-alpha.1.  
This issue can easily be fixed by creating a patch in the the config folder by specifying which container use but since I'm not sure how to do that I opened this issue.

**Comment by squaremo** [comment]
Hi, sorry for the garbled instructions. We're working toward this being part of `flux install`, but in the meantime, it's a bit janky.

It's worth being able to build the image locally, if you're keen to experiment, since it's moving fast(ish) you may want to get the latest code from time to time. `make docker-image` will build the image with whichever Docker you're pointed at.

If you're using Docker Desktop or minikube, that's enough to make it available to Kubernetes too.

If you're using Kind, you will need to "side load" it:

    kind load docker-image fluxcd/image-automation-controller

If you're hosting Kubernetes some other way, you will have to take other measures to make your locally built image available to it, and that may be a lot more trouble! In which case, you can use one of the published images by (as you suggested) patching the config:

```
$ mkdir ./config/scratch
$ cp -R config/default/* ./config/scratch
$ (cd config/scratch; kustomize edit set image fluxcd/image-automation-controller=fluxcd/image-automation-controller:v0.0.1-alpha.1)
$ kustomize build ./config/scratch | kubectl apply -f -
```

(NB the ./config/scratch directory needs to be a sibling to config/default, so that some relative paths in the copied kustomization. yaml work -- if you put it somewhere else, you'll need to fix those up)

**Comment by stefanprodan** [comment]
The image automation controllers can now be installed with `flux`, guide here https://toolkit.fluxcd.io/guides/image-update/
