### ISSUE TITLE
Include [skip ci] in the default commit message

### ISSUE THREAD

**Issue by squaremo** [fluxcd/image-automation-controller#52]
Some people like to keep their configuration alongside their application code, and set up CI to build images from the application code. This can cause problems when combined with Flux's automation, because commits from the automation will cause the CI to run (which builds another image, which causes the automation to run, ...).

Happily, many (most?) CI systems have a "get out clause": if you put a special token in a commit message, they will not run for that commit. For example, Circle CI uses `[ci skip]`: https://circleci.com/docs/2.0/skip-build/ (and someone summarised the support in a whole lot of systems here: https://github.community/t/github-actions-does-not-respect-skip-ci/17325/3).

By including this token in the default commit message (which people can change if they _don't_ want to skip CI for automated commits), the looping problem above will be avoided in a default install.

EDIT: expanded description.

**Comment by stefanprodan** [comment]
This will prevent further integrations like opening PRs with GitHub Actions, so we should allow users to disable it.

**Comment by fbrv** [comment]
Hi, if no one is working on this enhancement I can fix it, the solution will check if commit message is present `skip ci`, something like: 
```
!contains(github.event.head_commit.message, 'skip ci')
```
But at the same time there are at the moment at least other two message that can be used for skip the ci:  

- no ci
- ci skip

**Comment by kingdonb** [comment]
There was an attempt to resolve this, but it looks like it was closed unmerged. Should this be opt-in behavior?

Since there are different keywords and some systems like Jenkins even let you configure your own.

It looks like this has been addressed with a `messageTemplate` field and users can refer to the docs about how to incorporate "ci skip" or similar messages into their commit messages.

https://fluxcd.io/docs/components/image/imageupdateautomations/

Any reason to keep this open? I don't know if it would be proper to add this to the default message, as that might be a breaking change for some users.
